[[descriptions]]
= Description of selected parts of the transaction

Limited support for this, see {name-profile-org}.

== Query Request

=== Specification Identification
[source,xml,indent=0]
....
include::../files/ExampleSearchNoticeRequest.xml[tags=specification-identification]
....
<.> Always use the same specification identification for the request.

=== Business Process Type Identifier
[source,xml,indent=0]
....
include::../files/ExampleSearchNoticeRequest.xml[tags=business-process-type-identifier]
....
<.> See the other chapters of peppol to select the right business process type and its identifier.

=== Sender electronic address
[source,xml,indent=0]
....
include::../files/ExampleSearchNoticeRequest.xml[tags=sender-electronic-address]
....
<.> You have to fill your own sender id into this slot. The endpoint id is clarified in the type attribute of the slot.

=== Receiver electronic address
[source,xml,indent=0]
....
include::../files/ExampleSearchNoticeRequest.xml[tags=receiver-electronic-address]
....
<.> Here goes the address of the receiver of your query. The endpoint id is clarified in the type attribute of the slot.

== Query
=== Keywords
[source,xml,indent=0]
....
include::../files/ExampleSearchNoticeRequest.xml[tags=keywords]
....
<.> All keywords are collected as one single string. Just enter the desired keywords for your search as you would expect it from a searchbar. Select keywords for any parameter of your search as if searching for a specific procedure.

This slot is optional.

=== Form Type
[source,xml,indent=0]
....
include::../files/ExampleSearchNoticeRequest.xml[tags=form-type]
....
<.> Select the type from the given collection. Into the type-attribute of the slot is to fill with the listID of your source.
The type of the slotValue is a CollectionValueType, so you can enter more than one element. Each element has its own type, i.e. StringValueType.

The whole slot is optional.

=== Notice Type
[source,xml,indent=0]
....
include::../files/ExampleSearchNoticeRequest.xml[tags=form-type]
....
<.> Just like the form type, you may select the notice type, you want to search for. The ID of your list has to be filled into the type-attribute of the slot.

The type of the slotValue is a CollectionValueType, so you can enter more than one element. Each element has its own type, i.e. StringValueType. The whole slot is optional.

=== Classification
[source,xml,indent=0]
....
include::../files/ExampleSearchNoticeRequest.xml[tags=classification]
....
<.> The classification consists of the type of classification and the value. The type of classification is filled into the type-attribute in form of your listID.
Therefore, the type of your classification has to be the same for each element. Into the value tag goes the selected CPV, CPVsuppl or other code for your search request.

The type of the slotValue is a CollectionValueType, so you can enter more than one element. Each element has its own type, i.e. StringValueType, that you have to declare. The whole slot is optional.

=== Contract Nature
[source,xml,indent=0]
....
include::../files/ExampleSearchNoticeRequest.xml[tags=contract-nature]
....
<.> The type of the slotValue is a CollectionValueType, so you can enter more than one element. The selected listID has to be filled into the type-attribute of the slot.
<.> Each element has its own type, i.e. StringValueType, that you have to declare.
<.> The values were chosen to match the classification codes.

The whole slot is optional.

=== Place of Performance
[source,xml,indent=0]
....
include::../files/ExampleSearchNoticeRequest.xml[tags=place-of-performance]
....
<.> The type of the slotValue is a CollectionValueType, so you can enter more than one element. The selected listID has to be filled into the type-attribute of the slot. Each location is added in form of its NUTS-Code.

The whole slot is optional.

=== Procedure Type
[source,xml,indent=0]
....
include::../files/ExampleSearchNoticeRequest.xml[tags=procedure-type]
....
<.> The type of the slotValue is a CollectionValueType, so you can enter more than one element. The selected listID has to be filled into the type-attribute of the slot. The value of the slot is chosen from the list.

The whole slot is optional.

=== Submission language
[source,xml,indent=0]
....
include::../files/ExampleSearchNoticeRequest.xml[tags=submission-language]
....
<.> The type of the slotValue is a CollectionValueType, so you can enter more than one element. The selected listID has to be filled into the type-attribute of the slot. The value of the slot is chosen from the list.

The whole slot is optional.

=== Notice Identifier
[source,xml,indent=0]
....
include::../files/ExampleSearchNoticeRequest.xml[tags=notice-identifier]
....
<.> The type of the slotValue is a CollectionValueType, so you can enter more than one element. The UUID is matching with the id you get in your response.

The whole slot is optional.

=== Procedure Identifier
[source,xml,indent=0]
....
include::../files/ExampleSearchNoticeRequest.xml[tags=procedure-identifier]
....
<.> The type of the slotValue is a CollectionValueType, so you can enter more than one element. The UUID is matching with the logical id you get in your response.

The whole slot is optional.

=== Procedure legal basis
[source,xml,indent=0]
....
include::../files/ExampleSearchNoticeRequest.xml[tags=procedure-legal-basis]
....
<.> Insert the id of the legal base from which you draw the procedure.

The whole slot is optional.

=== Reserved Participation
[source,xml,indent=0]
....
include::../files/ExampleSearchNoticeRequest.xml[tags=reserved-participation]
....
<.> The type of the slotValue is a CollectionValueType, so you can enter more than one element. The selected listID has to be filled into the type-attribute of the slot. The value of the slot is chosen from the list. Choose if the procedure is only accessible for certain types of companys.

The whole slot is optional.

=== Suitable for SMEs
[source,xml,indent=0]
....
include::../files/ExampleSearchNoticeRequest.xml[tags=suitable-for-smes]
....
<.> As this slotValue is a boolean, please only insert true or false, if the procedure has to be suitable for small or medium sized economic operators.

The whole slot is optional.

=== Winner economic operator name
[source,xml,indent=0]
....
include::../files/ExampleSearchNoticeRequest.xml[tags=winner-economic-operator-name]
....
<.> Insert the official name of the company which won the procedure.

The whole slot is optional.

=== Award criterion type
[source,xml,indent=0]
....
include::../files/ExampleSearchNoticeRequest.xml[tags=award-criterion-type]
....
<.> The type of the slotValue is a CollectionValueType, so you can enter more than one element. The selected listID has to be filled into the type-attribute of the slot. The value of the slot is chosen from the list. Some of the values cannot be combined with each other, so be careful in selecting each.

The whole slot is optional.

=== Buyer Information
[source,xml,indent=0]
....
include::../files/ExampleSearchNoticeRequest.xml[tags=information-about-buyer]
....
<.> This slot collects all the information about the buyer.
<.> The number of the organisation, as defined in each country.
<.> The address of the company - city.
<.> The address of the company - postcode.
<.> The id of each affected subdivison of the company, as selected from the code list. The list id has to be deposit in the type attribute of the slot.
<.> The country code of each affected country, as selected from the code list. The list id has to be deposit in the type attribute of the slot.
<.> The legal type of the buying company, as selected from the code list. The list id has to be deposit in the type attribute of the slot.
<.> The main activity of the buying company, as selected from the code list. The list id has to be deposit in the type attribute of the slot.

The whole slot is optional.
