[[descriptions]]
= Description of selected parts of the transaction

The transaction is based upon the definitions of {name-transaction-org} described in {link-profile}. Business terms, Business rules and code lists used are inherited from the following {link-bii3} and {eforms-specs} and {regrep} documents:

== Query Request

=== Specification Identification
[source,xml,indent=0]
....
include::../files/ExampleSearchNoticeRequest.xml[tags=specification-identification]
....
<.> Identifier for the set of rules and transactions for a search notice request.
<.> The value for the specification identification is always "urn:fdc:peppol.eu:2021:pracc:t011:1.0", just like in the given example.

=== Business Process Type Identifier
[source,xml,indent=0]
....
include::../files/ExampleSearchNoticeRequest.xml[tags=business-process-type-identifier]
....
<.> Identifier for the business process context of the search notice response.
<.> The value for the business process type identifier is always "urn:fdc:peppol.eu:2021:pracc:p006:1.0", just like in the given example.

=== Issue Date Time
[source,xml,indent=0]
....
include::../files/ExampleSearchNoticeRequest.xml[tags=issue-date-time]
....
<.> Date and time when the request was being issued.
<.> The SlotValue type has to be DateTimeValueType you have to give stick to the format and add date and time granular to seconds and the timezone.

=== Sender electronic address
[source,xml,indent=0]
....
include::../files/ExampleSearchNoticeRequest.xml[tags=sender-electronic-address]
....
<.> The endpoint id is clarified in the type attribute of the slot.
<.> Fill the electronic sender address into this slot.

=== Receiver electronic address
[source,xml,indent=0]
....
include::../files/ExampleSearchNoticeRequest.xml[tags=receiver-electronic-address]
....
<.> The endpoint id is clarified in the type attribute of the slot.
<.> Fill the electronic receiver address into this slot

== Response Option
[source,xml,indent=0]
....
include::../files/ExampleSearchNoticeRequest.xml[tags=response-option]
....
<.> You have to include the response option with its default option "LeafClassWithRepositoryItem" to allow for the response to include the required repository items.

== Query
=== Keywords
[source,xml,indent=0]
....
include::../files/ExampleSearchNoticeRequest.xml[tags=keywords]
....
<.> All keywords are collected as one single string. Just enter the desired keywords for your search as you would expect it from a searchbar. Select keywords for any parameter of your search as if searching for a specific procedure.

This slot is optional and can only included once.

=== Form Type
[source,xml,indent=0]
....
include::../files/ExampleSearchNoticeRequest.xml[tags=form-type]
....
<.> Select the type from the given collection. Into the type-attribute of the slot is to fill with the listID of your source.
The type of the slotValue is a CollectionValueType, so you can enter more than one element. Each element has its own type, i.e. StringValueType.

This slot is optional and can only included once.

=== Notice Type
[source,xml,indent=0]
....
include::../files/ExampleSearchNoticeRequest.xml[tags=form-type]
....
<.> Just like the form type, you may select the notice type, you want to search for. The ID of your list has to be filled into the type-attribute of the slot.

The type of the slotValue is a CollectionValueType, so you can enter more than one element. Each element has its own type, i.e. StringValueType. This slot is optional and can only included once.

=== Classification
[source,xml,indent=0]
....
include::../files/ExampleSearchNoticeRequest.xml[tags=classification]
....
<.> The classification consists of the type of classification and the value. The type of classification is filled into the type-attribute in form of your listID.
Therefore, the type of your classification has to be the same for each element. Into the value tag goes the selected CPV or CPVsuppl code for your search request.

The type of the slotValue is a CollectionValueType, so you can enter more than one element. Each element has its own type, i.e. StringValueType, that you have to declare. The whole slot is optional.

=== Contract Nature
[source,xml,indent=0]
....
include::../files/ExampleSearchNoticeRequest.xml[tags=contract-nature]
....
<.> The type of the slotValue is a CollectionValueType, so you can enter more than one element. The selected listID has to be filled into the type-attribute of the slot.
<.> Each element has its own type, i.e. StringValueType, that you have to declare.
<.> The values were chosen to match the classification codes.

This slot is optional and can only included once.

=== Place of Performance
[source,xml,indent=0]
....
include::../files/ExampleSearchNoticeRequest.xml[tags=place-of-performance]
....
<.> The type of the slotValue is a CollectionValueType, so you can enter more than one element. The selected listID has to be filled into the type-attribute of the slot. Each location is added in form of its NUTS-Code.

This slot is optional and can only included once.

=== Estimated Value
[source,xml,indent=0]
....
include::../files/ExampleSearchNoticeRequest.xml[tag=estimatedValue]
....
<.> The slot for the tender value consists of four different slots, which can all be added to specify the tender value. The slot as a whole is optional, as are each of the three slots in it.
<.> The first one is minimum, the minimal tender value you are looking for. It has to be declared as a float.
<.> Corresponding to minimum, the second value you can search for in the tender value is the maximum. Just like the minimum the maximum tender value you are searching for is a float.
<.> The third possible criteria is the currency. This one is a CollectionValueType you can enter more than one element. The values are selected from the list which ID is deposited in the type-attribute of the slot.

This slot is optional and can only included once. If Estimated Value is included at least one of minimum, maximum or currency has to be included as well. These can only be included once.

=== Procedure Type
[source,xml,indent=0]
....
include::../files/ExampleSearchNoticeRequest.xml[tags=procedure-type]
....
<.> The type of the slotValue is a CollectionValueType, so you can enter more than one element. The selected listID has to be filled into the type-attribute of the slot. The value of the slot is chosen from the list.

This slot is optional and can only included once.

=== Submission language
[source,xml,indent=0]
....
include::../files/ExampleSearchNoticeRequest.xml[tags=submission-language]
....
<.> The type of the slotValue is a CollectionValueType, so you can enter more than one element. The selected listID has to be filled into the type-attribute of the slot. The value of the slot is chosen from the list.

This slot is optional and can only included once.

=== Publication Date
[source,xml,indent=0]
....
include::../files/ExampleSearchNoticeRequest.xml[tags=publication-date]
....
<.> The first of four date slots. Here you can search for the date of publication. The slot can consist of up to two slots, each of a DateTimeValueType.
<.> The first slot can be filled with a potential start date and time of the publication. With the DateTimeValueType in mind you can declare the desired date in the standard DateTime format.
<.> The second slot can be filled with a possible end date and time of the publication. With the DateTimeValueType in mind you can declare the desired date in the standard DateTime format.

This slot is optional and can only included once.

=== Deadline Receipt Tenders
[source,xml,indent=0]
....
include::../files/ExampleSearchNoticeRequest.xml[tags=deadline-receipt-tenders]
....
<.> The second of four date slots. Here you can search for the deadline of receipt tenders. The slot can consist of up to two slots, each of a DateTimeValueType.
<.> The first slot can be filled with a potential start date and time for the deadline for receipt tenders. With the DateTimeValueType in mind you can declare the desired date in the standard DateTime format.
<.> The second slot can be filled with a possible end date and time for the deadline for receipt tenders. With the DateTimeValueType in mind you can declare the desired date in the standard DateTime format.

This slot is optional and can only included once.

=== Additional Information Deadline
[source,xml,indent=0]
....
include::../files/ExampleSearchNoticeRequest.xml[tags=additional-information-deadline]
....
<.> The third of four date slots. Here you can search for the deadline of additional information. The slot can consist of up to two slots, each of a DateTimeValueType.
<.> The first slot can be filled with a potential start date and time for the deadline of additional information. With the DateTimeValueType in mind you can declare the desired date in the standard DateTime format.
<.> The second slot can be filled with a possible end date and time for the deadline of additional information. With the DateTimeValueType in mind you can declare the desired date in the standard DateTime format.

This slot is optional and can only included once.

=== Deadline Receipt Requests
[source,xml,indent=0]
....
include::../files/ExampleSearchNoticeRequest.xml[tags=deadline-receipt-requests]
....
<.> The last of the four date slots. Here you can search for the deadline of receipt requests. The slot can consist of up to two slots, each of a DateTimeValueType.
<.> The first slot can be filled with a potential start date and time for the deadline of receipt requests. With the DateTimeValueType in mind you can declare the desired date in the standard DateTime format.
<.> The second slot can be filled with a possible end date and time for the deadline  of receipt requests. With the DateTimeValueType in mind you can declare the desired date in the standard DateTime format.

This slot is optional and can only included once.

=== Notice Identifier
[source,xml,indent=0]
....
include::../files/ExampleSearchNoticeRequest.xml[tags=notice-identifier]
....
<.> The type of the slotValue is a CollectionValueType, so you can enter more than one element. The UUID is matching with the id you get in your response.

This slot is optional and can only included once.

=== Procedure Identifier
[source,xml,indent=0]
....
include::../files/ExampleSearchNoticeRequest.xml[tags=procedure-identifier]
....
<.> The type of the slotValue is a CollectionValueType, so you can enter more than one element. The UUID is matching with the logical id you get in your response.

This slot is optional and can only included once.

=== Procedure legal basis
[source,xml,indent=0]
....
include::../files/ExampleSearchNoticeRequest.xml[tags=procedure-legal-basis]
....
<.> Insert the id of the legal base from which you draw the procedure.

This slot is optional and can only included once.

=== Reserved Participation
[source,xml,indent=0]
....
include::../files/ExampleSearchNoticeRequest.xml[tags=reserved-participation]
....
<.> The type of the slotValue is a CollectionValueType, so you can enter more than one element. The selected listID has to be filled into the type-attribute of the slot. The value of the slot is chosen from the list. Choose if the procedure is only accessible for certain types of companies.

This slot is optional and can only included once.

=== Suitable for SMEs
[source,xml,indent=0]
....
include::../files/ExampleSearchNoticeRequest.xml[tags=suitable-for-smes]
....
<.> As this slotValue is a boolean, please only insert true or false, if the procedure has to be suitable for small or medium sized economic operators.

This slot is optional and can only included once.

=== Winner economic operator name
[source,xml,indent=0]
....
include::../files/ExampleSearchNoticeRequest.xml[tags=winner-economic-operator-name]
....
<.> Insert the official name of the company which won the procedure.

This slot is optional and can only included once.

=== Award criterion type
[source,xml,indent=0]
....
include::../files/ExampleSearchNoticeRequest.xml[tags=award-criterion-type]
....
<.> The type of the slotValue is a CollectionValueType, so you can enter more than one element. The selected listID has to be filled into the type-attribute of the slot. The value of the slot is chosen from the list. Some of the values cannot be combined with each other, so be careful in selecting each.

This slot is optional and can only included once.

=== Buyer Information
[source,xml,indent=0]
....
include::../files/ExampleSearchNoticeRequest.xml[tags=information-about-buyer]
....
<.> This slot collects all the information about the buyer.
<.> The number of the organisation, as defined in each country.
<.> The address of the company - city.
<.> The address of the company - postcode.
<.> The id of each affected subdivision of the company, as selected from the code list. The list id has to be deposited in the type attribute of the slot. Multiple can be added.
<.> The country code of each affected country, as selected from the code list. The list id has to be deposited in the type attribute of the slot. Multiple can be added.
<.> The legal type of the buying company, as selected from the code list. The list id has to be deposited in the type attribute of the slot. Multiple can be added.
<.> The main activity of the buying company, as selected from the code list. The list id has to be deposited in the type attribute of the slot. Multiple can be added.

The whole slot is optional and can be included multiple times. If Buyer Information is included at least one of name, organisation number, city, postcode, organisation country subdivision, country code, legal type or main activity has to be included as well. These can only be included once.
