# This is a basic workflow to help you get started with Actions

name: build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-site:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: crate target
        run: mkdir -p ./target/site/files
      - name: build target
        run: ./tools/bin/build.sh
      - name: create site.zip
        run: zip -qr ./target/site.zip ./target/site/
      - uses: actions/upload-artifact@v2
        with:
          name: site
          path: ./target/site.zip
